# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {DRC 23-20}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/CPU_single_cycle/CPU_single_cycle.cache/wt [current_project]
set_property parent.project_path C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/CPU_single_cycle/CPU_single_cycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_mem C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/Ins_Memory/code.mem
read_verilog -library xil_defaultlib {
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/ALU/ALU32.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/CPU_top.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/Control_unit/Control_unit.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/Data_Memory/Data_Memory.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/Extend.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/Ins_Memory/Ins_Memory.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/PC.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/RegFile/RegFile.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/DEBUG/clkdiv_190hz.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/DEBUG/debouncing.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/DEBUG/displayReg.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/mux2to1_32.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/mux2to1_5.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/mux4to1.v
  C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/src/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/CPU_single_cycle/CPU_single_cycle.srcs/constrs_1/new/my.xdc
set_property used_in_implementation false [get_files C:/Users/yyhyplxyz/Desktop/CPU_single_cycle-revised/CPU_single_cycle/CPU_single_cycle.srcs/constrs_1/new/my.xdc]


synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
